{%- if page.comments %}
  <div class="comments" id="comments">
    <script src="https://giscus.app/client.js"
            data-repo="Cloudspots/hexo"
            data-repo-id="R_kgDOTlDRCw"
            data-category="Announcements"
            data-category-id="DIC_kwDOTlDRC84DCcbb"
            data-mapping="pathname"
            data-strict="0"
            data-reactions-enabled="1"
            data-emit-metadata="1"
            data-input-position="top"
            data-theme="preferred_color_scheme"
            data-lang="en"
            crossorigin="anonymous"
            async>
    </script>
  </div>
{%- endif %}
